CREATE TABLE USERS (
  username VARCHAR2(20) NOT NULL,
  password_hash CHARACTER (64) NOT NULL,
  first_name VARCHAR2(20) NOT NULL,
  last_name VARCHAR2(20) NOT NULL
);

ALTER TABLE USERS ADD CONSTRAINT USERS_PK PRIMARY KEY (username);

CREATE TABLE NOTES (
  note_id NUMBER(20) NOT NULL,
  username VARCHAR2(20) NOT NULL,
  note_text VARCHAR2(400) NOT NULL
);

ALTER TABLE NOTES ADD CONSTRAINT NOTES_PK PRIMARY KEY (note_id);

ALTER TABLE NOTES ADD CONSTRAINT NOTES_USERS_FK FOREIGN KEY (username) REFERENCES USERS (username);

CREATE SEQUENCE seq_notes;

COMMIT;

